update 211202题目排版和示例代码
talkgo/learning pull request #21
Opened 2021-12-06 02:15 UTC by dowell2020

2021-12-06 15:49 UTC, yangwenmai requested changes

2021-12-06 15:49 UTC, yangwenmai commented on content/docs/algorithms/algs/008.md
> +```
去掉 ``` 的注释

2021-12-06 15:49 UTC, yangwenmai commented on content/docs/algorithms/algs/008.md
> +
去除多余空行

2021-12-06 15:49 UTC, yangwenmai commented on content/docs/algorithms/algs/008.md
> +
去除多余空行

2021-12-06 15:49 UTC, yangwenmai commented on content/docs/algorithms/algs/008_key/dowell.md
> +### 211202作业
数字和中文之间要有空格

2021-12-06 15:49 UTC, yangwenmai commented on content/docs/algorithms/algs/008_key/dowell.md
> +
去除多余空行

2021-12-06 15:49 UTC, yangwenmai commented on content/docs/algorithms/algs/008_key/dowell.md
> +```
```suggestion
```golang
```

2021-12-06 15:49 UTC, yangwenmai commented on content/docs/algorithms/algs/008_key/dowell.md
> +
去除多余空行

2021-12-09 12:22 UTC, dowell2020 commented
修改了多余的空格和```

2021-12-10 05:48 UTC, yangwenmai approved these changes

2021-12-10 05:48 UTC, merged